from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime

class EmbeddingVector(BaseModel):
    """
    Represents the vector representation of text chunks generated by Cohere API, stored in Qdrant.
    """
    id: str
    vector: List[float]
    chunk_id: str
    model: str
    created_at: datetime = datetime.now()
    dimension: int

    def validate_vector(self) -> bool:
        """Validate that the vector has the correct dimension."""
        return len(self.vector) == self.dimension